development:
  adapter: postgresql
  database: kremlin_development
  host: localhost
  username: moizkmalik
  password:

test:
  adapter: postgresql
  database: kremlin_test
  host: localhost
  username: moizkmalik
  password: